language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: chrisleavitt-github
    token:
      secure: b1bf754de1ccdb78ccf44d1ebe7baa34adf28555
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
